#!/usr/bin/env bash
# tests/F13-tea-smoke.sh — valida a forma de um <FXX>-test-plan.md
# contra docs/F13-test-plan-spec.md.
#
# Usage: tests/F13-tea-smoke.sh <feature-dir> <FXX>
#
# Exit 0 se forma OK, !=0 se algum check falha.

set -euo pipefail

DIR="${1:?feature dir required}"
FXX="${2:?fxx id required (e.g. FX1)}"

PLAN="$DIR/${FXX}-test-plan.md"
[[ -f "$PLAN" ]] || { echo "FAIL: $PLAN not found"; exit 1; }

# Section presence
fail=0
for section in "# Test Plan" "## Fixtures" "## Harnesses" "## Perf budgets" "## Mocks vs hits real" "## Test scenarios resumo" "## Anotações"; do
  if ! grep -qF "$section" "$PLAN"; then
    echo "FAIL: missing section: $section"
    fail=1
  fi
done

# Header lines
grep -q "^\*\*Status:\*\* drafted" "$PLAN" || { echo "FAIL: missing **Status:** drafted"; fail=1; }
grep -q "^\*\*Generated by:\*\* TEA" "$PLAN" || { echo "FAIL: missing **Generated by:** TEA"; fail=1; }
grep -qE "^\*\*Generated at:\*\* [0-9]{4}-" "$PLAN" || { echo "FAIL: missing or malformed **Generated at:**"; fail=1; }

# Fixtures table has at least one data row (line starting with "|" + "|")
fixture_rows=$(awk '/## Fixtures/,/## Harnesses/' "$PLAN" | grep -cE '^\| [^|]+\| [^|]+\|' || true)
if [[ "$fixture_rows" -lt 2 ]]; then  # 1 header + ≥1 data
  echo "FAIL: Fixtures table needs ≥1 data row"; fail=1
fi

# Subsections in Harnesses
for sub in "#### Unit" "#### Integration" "#### E2E"; do
  if ! grep -qF "$sub" "$PLAN"; then
    echo "FAIL: missing harness subsection: $sub"; fail=1
  fi
done

# At least one task ID referenced in "Anotações"
if ! awk '/## Anotações/,EOF' "$PLAN" | grep -qE "${FXX}-T[0-9]+"; then
  echo "FAIL: Anotações does not reference any ${FXX}-Txx task"; fail=1
fi

if [[ $fail -ne 0 ]]; then
  echo "FAIL: smoke verification failed"
  exit 1
fi
echo "OK: $PLAN passes F13 spec smoke"
